/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Demo1;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Assert;
import org.junit.Before;

public class LibraryTest {
	@Before
	public void beforeEveryTesr() {
	System.out.println("-------------------------------");
	}

	@Test
	
	public void given_FirstNameis_Valid() {
	Example example =new Example();
	boolean result =Example.validatefirstname("Kartik");
	Assert.assertTrue("Happy",result);
}
	@Test
	
	public void given_FirstNameis_In_Valid() {
	Example example =new Example();
	boolean result =Example.validatefirstname("kartik");
	Assert.assertTrue("Sad",result);
}
@Test
	
	public void given_lastNameis_Valid() {
	Example example =new Example();
	boolean result =Example.validatelastname("Kavi");
	Assert.assertTrue("Happy",result);
}
	@Test
	
	public void given_lastNameis_In_Valid() {
	Example example =new Example();
	boolean result =Example.validatelastname("kavi");
	Assert.assertTrue("Sad",result);
}

	@Test
	
	public void given_emailId_is_Valid() {
	Example example =new Example();
	boolean result = Example.validatemailId("kartik123@gmail.com");
	Assert.assertTrue("Happy",result);
}
@Test
	
	public void given_emailId_is_In_Valid() {
	Example example =new Example();
	boolean result = Example.validatemailId("karti@123");
	Assert.assertTrue("Sad",result);
}
	@Test
	
	public void given_Password_Valid() {
	Example example =new Example();
	boolean result = Example.validatepassword("Kaartik@123");
	Assert.assertTrue("Happy",result);
}
@Test
	
	public void given_Password_Is_In_Valid() {
	Example example =new Example();
	boolean result = Example.validatepassword("Kaartik123");
	Assert.assertTrue("Sad",result);
}

	@Test
	
	public void given_Mobilenum_Valid() {
	Example example =new Example();
	boolean result = Example.validatemobilenum("7768059099");
	Assert.assertTrue("Happy",result);
}
@Test
	
	public void given_Mobilenum_In_Valid() {
	Example example =new Example();
	boolean result = Example.validatemobilenum("68059887099");
	Assert.assertTrue("Sad",result);
}

       
}
