/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Demo1;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Assert;
import org.junit.Before;

public class LibraryTest {
	@Before
	public void beforeEveryTesr() {
	System.out.println("-------------------------------");
	}

	@Test
	
		public void firstname() {
		Example example =new Example();
		Assert.assertTrue(Example.validatefirstname("Llit"));
		System.out.println("pass");
	}
	
	@Test
	
	public void emailId() {
	Example example =new Example();
	Assert.assertTrue(Example.validatemailId("kartik123@gmail.com"));
}
	@Test
	
	public void password() {
	Example example =new Example();
	Assert.assertTrue(Example.validatepassword("Kaartik@123"));
}
	@Test
	
	public void mobilenum() {
	Example example =new Example();
	Assert.assertTrue(Example.validatemobilenum("7768059099"));
}
       
}
